X1337 = "https://www.1377x.to"
TGX = "https://torrentgalaxy.info"
TORLOCK = "https://www.torlock2.com"
PIRATEBAY = "https://thepiratebay10.xyz"
NYAASI = "https://nyaa.si"
ZOOQLE = "https://pimpmymind.net"
KICKASS = "https://kickasstorrents.bz"
BITSEARCH = "https://bitsearch.eu"
MAGNETDL = "https://magnetdl.co"
LIBGEN = "https://libgen.li"
YTS = "https://yts.gg"
LIMETORRENT = "https://www.limetorrents.fun"
TORRENTFUNK = "https://www.torrentfunk.com"
GLODLS = "https://www.torrentdownloads.pro"
TORRENTPROJECT = "https://torrentproject.cc"
YOURBITTORRENT = "https://yourbittorrent.com"

EXTRATORRENT = "https://extratorrent.st"
